version: '3'

tasks:
  build:
    cmds:
      - go build -o linkcheker cmd/linkchecker/main.go
    silent: true

  test:
    cmds:
      - go test ./...

  coverage:
    cmds:
      - go test ./... -coverprofile=coverage.out