version: '3'

tasks:
  build:
    cmds:
      - go build -o linkcheker cmd/linkchecker/main.go
    silent: true

  test:
    cmds:
      - go test ./... {{.CLI_ARGS}}

  test-all:
    cmds:
      - go test ./... --tags=integration {{.CLI_ARGS}}

  coverage:
    cmds:
      - go test ./... --tags=integration -coverprofile=coverage.out