version: '3'

tasks:
  build:
    cmds:
      - go build -o linkchecker cmd/linkchecker/main.go
    silent: true

  test:
    cmds:
      - go test ./... {{.CLI_ARGS}}

  coverage:
    cmds:
      - go test ./... -coverprofile=coverage.out
