version: '3'

tasks:
  build:
    cmds:
      - go build -ldflags="-X main.Version={{.VERSION}} -X main.GitCommit={{.GIT_COMMIT}}" -o bin/linkchecker cmd/linkchecker/main.go
    vars:
      VERSION:
        sh: git describe --tags
      GIT_COMMIT:
        sh: git rev-list -1 HEAD

  test:
    cmds:
      - go test ./... {{.CLI_ARGS}}

  coverage:
    cmds:
      - go test ./... -coverprofile=coverage.out
