version: '3'

tasks:
  build:
    cmds:
      - go build -ldflags="$LDFLAGS" -o bin/linkchecker cmd/linkchecker/main.go
    vars:
      VERSION:
        sh: git describe --tags
      GIT_COMMIT:
        sh: git rev-list -1 HEAD
    env:
      LDFLAGS: "-X main.Version={{.VERSION}} -X main.GitCommit={{.GIT_COMMIT}}"

  test:
    cmds:
      - go test ./... {{.CLI_ARGS}}

  coverage:
    cmds:
      - go test -v ./... -race -coverprofile=coverage.out -covermode=atomic
