name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./... -race -coverprofile=coverage.out -covermode=atomic

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v3

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
